### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [lukasbystricky/mary-parker-follett_the-new-state#1]
- [ ] Since the chapters are numbered consecutively, the file names/ids don't need the part prefixes, i.e. should be just "chapter-X," [SEMoS 2.2.4.3](https://standardebooks.org/manual/1.8.0/single-page#2.2.4.3).
- [ ] The introduction begins with the uppercased OUR. I assume it didn't get caught in the update to the rest of the chapters.
- [ ] CMS says that references to chapters (and other parts of a book) are lowercased, so the capitalization in the endnotes (d3830b9) should be reverted.
- [ ] Also, why did you not keep the links to the chapters in the endnotes?
- [ ] I'm not a French speaker; why do you think the oú in the French quote in ch. 29 is incorrect?
- [ ] Replacing quotes with italics on publications isn't editorial, e.g. see d35c7c5, so 866ce61 should not be editorial, either.
- [ ] Conversely, I believe a8dc0c7 (a b c -> A.B.C.) is editorial, as is the "Versus" to "versus" portion of 8fd5b86.
- [ ] In d35c7c, you expanded a ch. to Chapter, which is editorial; that will need to be split out from the rest of the commit.
- [ ] Endnote 105 references the untagged New Age, which is tagged as a journal in ch. 28.
- [ ] Chapter ranges qualify for [SEMoS 8.7.7.5](https://standardebooks.org/manual/1.8.0/single-page#8.7.7.5), even if they're roman numeral, so the hyphens should be en-dashes.
- [ ] Typogrify catches an "eoc" that should be added in ch. 1.
- [ ] The formatting for the subtitles in ch. 24–26 and 30 should be handled with a selector in CSS, not with `<i>`.
- [ ] The `body[xml|lang]` CSS should be `blockquote[xml|lang]`, [SEMoS 8.2.9.6](https://standardebooks.org/manual/1.8.0/single-page#8.2.9.6). We need to correct the 5.3.1.3 reference.
- [ ] The headers on the sub-chapters in ch. 6 should probably be h# instead. Whether they're in the scan's ToC is irrelevant; our ToC's often don't agree. This would also correct the current formatting issues with the headers.
- [ ] I'm not sure the CSS trick for the opening quotes in ch. 27 is going to work. Not only do we generally not want absolute positioning in an ebook, it doesn't display correctly (no opening quote) in Apple Books (iOS or Mac), and that's usually the platform with the best CSS support. I'm happy to leave it for Alex if you want to keep it. Since they're in a blockquote, I would argue the quotes aren't needed, anyway.
- [ ] Since _Harvard Law Review_ is referred to unabbreviated, maybe expand it elsewhere? But that's just a suggestion, feel free to ignore it. :)
- [ ] Droit is in M-W, so (on its own) does not need italics.
- [ ] We don't use proper names in the short description, [SEMoS 9.6.1.2](https://standardebooks.org/manual/1.8.0/single-page#9.6.1.2).
- [ ] No change needed, but just for future reference, the "select words" modernize spelling (14df60e) can be done as part of the overall "Modernize hyphenation and spelling" commit (see step 15 of the Step by Step guide). Also, we do want to call it "Modernize hyphenation and spelling," to alert those who care that we changed both.
- [ ] I don't think using "part" for both levels of part 3 is correct, but I've asked about it three times and never gotten an answer. I'll leave it with Alex.

**Comment by lukasbystricky** [comment]
Thanks Vince! It's really great to have a second set of eyes on this. Always surprised at how much I miss. Mostly done, just a few comments.

- My thinking was that in an ebook links to specific chapters are unnecessary since the reader always has a ToC handy. It's also not standard practice to have those (or is it?). 
- oú is not a word (at least in modern French), but it turns out this was actually a transcription error so I've updated the commit to reflect that. 
- I think I've used similar tricks like that before, but maybe Alex has a better idea.
- droit should not be italicized in general, but I think the two times I kept the italics make sense in context because she's explicitly referring to the French word. I'd earlier removed the italics on droit in cases where it wasn't clearly the French word.  
- The short description has been rephrased, but for the record that particular rule is very loosely enforced (see the [opds feed](https://standardebooks.org/feeds/opds/all)). It seems like the unwritten rule is that author names are allowed. Might be worth clarifying with Alex. 
- I remember the discussion on parts, but I don't recall a clear answer there either.

**Comment by vr8hub** [comment]
Yeah, I used to think I was one day going to have one sail through with no changes, and I've realized that's never going to happen. :)

Re the links, this for sure isn't a have to, but since there _were_ links, I just thought it would be nice to keep them. There is no standard practice, because there normally aren't links.

Re the CSS, yes, I'll leave it with him.

I see on the droits, and you're right, those two instances are fine.

I miss things, others miss things, rules change over time, there are lots of ways we get exceptions in the corpus. But if there's a current rule in SEMoS, then that's what I follow in reviews. I'm always happy to have the rules clarified (see the "parts" issue :) ).

Just as a note, it's fine as is, but targeting `[epub|type]="subtitle"` might have been clearer for the CSS.

Everything looks good, I'll hand it over to Alex.

**Comment by lukasbystricky** [comment]
Yeah I'm not sure that I found the clearest/most robust way to do it, but I didn't want to use "subtitle" because that would have hit the one in the half title page. 

Thanks again for the review.
